networks:
  isp-network:
    driver: bridge

services:
  cms:
    container_name: isp_cms
    build:
      context: ./drupal
      dockerfile: cms.Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./drupal/files:/opt/drupal/web/sites/default/files
      - ./drupal/siteground/modules/custom:/opt/drupal/web/modules/custom
      - ./drupal/siteground/themes/custom:/opt/drupal/web/themes/custom
      - ./drupal/siteground/config/sync:/opt/drupal/config/sync
    networks:
      - isp-network
  db:
    container_name: isp_db
    image: arm64v8/mysql
    environment:
      MYSQL_DATABASE: 'islandstrength'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - 3306
    restart: always
    volumes:
      - ./data/database/data:/var/lib/mysql
    networks:
      - isp-network 
