<?php

/**
 * @file
 * Custom hook functions.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_form_FORM_ID_alter()
 */
function island_strength_power_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (stripos($form_id, 'webform_submission_event_signup_form') !== false) {
    $path = \Drupal::service('path.current')->getPath();
    $params = \Drupal\Core\Url::fromUserInput($path)->getRouteParameters();

    if (!empty($params['node'])) {
      $node = Node::load($params['node']);
      $form['elements']['payment']['payment_form']['#stripe_amount'] = (string) $node->field_registration_price->value;
    }
  }
}
